version: "3.9"

services:
  node_app:
    container_name: node_app
    build: .
    image: lelequinter/node_live_app
    ports:
      - "3000:3000"
    environment:
      - PG_DB=node_live_db
      - PG_USER=lelequinter
      - PG_PASSWORD=123456
      - PG_HOST=node_db
      - SALT_ROUNDS=6
      - JWT_SECRET=superbsecure
    restart: always
    depends_on:
      - node_db
  
  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=node_live_db
      - POSTGRES_USER=lelequinter
      - POSTGRES_PASSWORD=123456
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}