version: "3.9"

services:
  node_app:
    container_name: node_app
    build: .
    image: lelequinter/node_live_app
    ports:
      - "3000:3000"
    environment:
      - PG_DB=${PG_DB}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_HOST=${PG_HOST}
      - SALT_ROUNDS=${SALT_ROUNDS}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - MB_URL_SUGGEST=${MB_URL_SUGGEST}
      - MB_URL_RETRIEVE=${MB_URL_RETRIEVE}
      - MB_URL_FORWARD=${MB_URL_FORWARD}
      - MB_ACCESS_TOKEN=${MB_ACCESS_TOKEN}
      - MB_SESSION_TOKEN=${MB_SESSION_TOKEN}
      - MB_SEARCH=${MB_SEARCH}
    restart: always
    depends_on:
      - node_db
  
  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}